// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH8JBWglwCTjfqUOopXVPk_pt526VEcXc',
    appId: '1:954378346494:web:8913ab769fe0c14d5caaaf',
    messagingSenderId: '954378346494',
    projectId: 'flutter-yt-d7403',
    authDomain: 'flutter-yt-d7403.firebaseapp.com',
    storageBucket: 'flutter-yt-d7403.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfIL5bSvr7_n2LHTpmXWvXH-p32xA7nnU',
    appId: '1:954378346494:android:13166624e82827cd5caaaf',
    messagingSenderId: '954378346494',
    projectId: 'flutter-yt-d7403',
    storageBucket: 'flutter-yt-d7403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC01u1eaDfadRiQEx6uvdBsk984rI_MbY0',
    appId: '1:954378346494:ios:e769100ec46acfc55caaaf',
    messagingSenderId: '954378346494',
    projectId: 'flutter-yt-d7403',
    storageBucket: 'flutter-yt-d7403.appspot.com',
    iosBundleId: 'com.example.firebaseyt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC01u1eaDfadRiQEx6uvdBsk984rI_MbY0',
    appId: '1:954378346494:ios:4ee0a5438bc5e20f5caaaf',
    messagingSenderId: '954378346494',
    projectId: 'flutter-yt-d7403',
    storageBucket: 'flutter-yt-d7403.appspot.com',
    iosBundleId: 'com.example.firebaseyt.RunnerTests',
  );
}
